### ISSUE TITLE
New breakage!

### ISSUE THREAD

**Issue by guygastineau** [exercism/scheme-test-runner#33]
@ErikSchierboom 

Somehow the tests are failing now in the automated test runner.  Here I have a screenshot of my solution to `rna-transcription` failing in the automated runner.  I dumped it into a new test directorty here though, and I don't get the `syntax error` result.json.  I get a passing `results.json`.  The opacity of the website's process of running these exercises makes it very hard for me to figure out why this is happening when all of our tests are passing.

![2022-06-16_09:49:00_selected](https://user-images.githubusercontent.com/38230885/174086223-ba79eac7-03e0-48a9-8d61-74220b6d24e8.png)

---

Here is a dump of the `results.json` I get when I run the test-runner tests locally including my rna-transcription exercise.

``` json
{"version": 2, "status": "pass", "tests": [{"name": "Empty RNA sequence", "status": "pass", "output": null, "test_code": "(equal? (dna->rna \"\") \"\")\n"}, {"name": "RNA complement of cytosine is guanine", "status": "pass", "output": null, "test_code": "(equal? (dna->rna \"C\") \"G\")\n"}, {"name": "RNA complement of guanine is cytosine", "status": "pass", "output": null, "test_code": "(equal? (dna->rna \"G\") \"C\")\n"}, {"name": "RNA complement of thymine is adenine", "status": "pass", "output": null, "test_code": "(equal? (dna->rna \"T\") \"A\")\n"}, {"name": "RNA complement of adenine is uracil", "status": "pass", "output": null, "test_code": "(equal? (dna->rna \"A\") \"U\")\n"}, {"name": "RNA complement", "status": "pass", "output": null, "test_code": "(equal? (dna->rna \"ACGTGGTCTTAA\") \"UGCACCAGAAUU\")\n"}]}
```

**Comment by ErikSchierboom** [comment]
@guygastineau The test runner returns the following in production: `{"version":2,"status":"error","message":"Syntax error","tests":null}`

I'll try to dig a bit deeper.

**Comment by guygastineau** [comment]
Thank you!

**Comment by ErikSchierboom** [comment]
I can at the very least confirm that the docker image works locally, so it should be some environment-specific issue.

**Comment by ErikSchierboom** [comment]
Could it somehow be due to https://github.com/exercism/scheme/pull/262?

**Comment by guygastineau** [comment]
Well, it didn't happen until that PR.  The new tests are tested against here though.  It might be due to a misconfiguration in the per exercise or track-wide json config?  I tried to update the config.json stuff to indicate that we have two test files "test-util.scm" and "test.scm" for each exercise, but maybe I messed it up.

**Comment by ErikSchierboom** [comment]
@guygastineau No, that should be fine. It does not make sense as locally I've updated to the latest version and that works.

**Comment by guygastineau** [comment]
I know.  This is pretty confusing :/

**Comment by guygastineau** [comment]
I have to go to the gym, and I have some other work this afternoon, but I can be responsive throughout the afternoon here, EST, if we figure this out.  I figure it is getting later where you are though, and you shouldn't spend your whole evening on this.  I appreciate your time helping me with this :heart:

**Comment by guygastineau** [comment]
Are you able to see output from the test-runner on `stderr` from the docker image running the tests?  The `Syntax error` message only occurs from one place in the code.  It is asimplification to shield users/students from weird outout, but I make the test-runner print the exception out to `stderr` with a format like `"Non-fatal error: %s\n"`.  So, reading the `stderr` of the docker running the test for the site will give us a clue if it is available.

**Comment by iHiD** [comment]
Erik's finished for the day now.
`stderr` is `Non-fatal error: (error assoc \"improperly formed alist ~s\" GC)\n"`

**Comment by guygastineau** [comment]
@iHiD I pinged you at exercism/scheme-test-runner#34 .  It now provides the full, raw output from both scheme implementations we try running the solutions whereas the previous output from stderr was just the first token of the output.

**Comment by iHiD** [comment]
I've merged that. Give it 10 then rerun your solution and I'll get the latest stderr for you?

**Comment by guygastineau** [comment]
I am still at the gym.  Somehow it seems to have resolved itself.  I don't know how that would happen or what it means, but only trying from my phone (very difficult) it appears the solution ran and is passing all tests now.

**Comment by guygastineau** [comment]
Nevermind.  I got back to my laptop and upgraded the exercise again.  It fails with the same error.  If you are still up, @iHiD, there should be new stderr output now.

**Comment by ErikSchierboom** [comment]
With your recently merged PR, stderr is now much more helpful:

```shell
Non-fatal error: (error assoc "improperly formed alist ~s" GC)
chez output: "((test-lib-version . 1) (status . ok) (pass (description . \"Say Hi!\") (code test-success \"Say Hi!\" equal? hello-world (quote ()) \"Hello, World!\") (stdout . \"\")))"
guile output: "GC Warning: Marker thread creation failed, errno = 1\
error creating finalization thread: Operation not permitted\
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0\
;;;       or pass the --no-auto-compile argument to disable.\
;;; compiling /mnt/exercism-iteration/test.scm\
;;; /mnt/exercism-iteration/test.scm:7:0: warning: possibly unbound variable `run-with-cli'\
;;; compiled /root/.cache/guile/ccache/2.2-LE-8-3.A/mnt/exercism-iteration/test.scm.go\
;;; compiling /mnt/exercism-iteration/test-util.ss\
;;; compiled /root/.cache/guile/ccache/2.2-LE-8-3.A/mnt/exercism-iteration/test-util.ss.go\
;;; compiling /mnt/exercism-iteration/hello-world.scm\
;;; compiled /root/.cache/guile/ccache/2.2-LE-8-3.A/mnt/exercism-iteration/hello-world.scm.go\
((test-lib-version . 1) (status . ok) (pass (description . \"Say Hi!\") (code test-success \"Say Hi!\" equal? hello-world (quote ()) \"Hello, World!\") (stdout . \"\")))"
```

Hopefully this helps you pin down the error.

**Comment by guygastineau** [comment]
Thank you!  This is a weird error/warning.  It is pretty self explanatory, but why is it happening?  Googling it is unhelpful at best, but somehow the socker containers running the tests in prod have some sort of different environment rules I guess.  

Strange as well is that this is a `GC warning`, not an error, but it is not commented which is why we are having the problem.  We are still getting the results as expected after the GC warning.  Is guile running without GC finalization in the docker container? Weird.

---

This has shown me a few things though.  The test runner should be able to handle when one scheme implementation fails catastrophically while the other runs.  Currently, one implementation failing reports a syntax error for both.  It wouldn't be a big deal given that missing identifiers and modules and whatnot all get reported robustly through the test system, but this bug highlights an important edge case where we don't need to fail outright.

I'll have some time to work on this this afternoon EST.

**Comment by guygastineau** [comment]
Okay, well for the time being I guess we can just make the test resilient to this error.  Part of this resilience will come from using `open-process-ports`, so we can treat stderr separately.  The issue with running guile here is that stderr is just redirected to stdout when using the less general `process`.  I will post a PR in probably less than an hour and link to it from here.  My goal will be to log things when they are wrong like this without forcing a syntax error on the user unless both implementations fail.

**Comment by guygastineau** [comment]
#35 should fix the current issues even though the weird GC error in the docker containers is still a mystery.

**Comment by guygastineau** [comment]
Finally, some things are passing in the production test runner again.  I am going to do one more test where the solution purposefully fails Chez in order to make sure we are getting results from successful guile runs now... and it works!

**Comment by ErikSchierboom** [comment]
Yay!
